# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-05 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/Users/stuartmcintosh/Code/Python/treehouse_projects/social_team_builder/social_team_builder/social_team_builder/static/media/default_avatar.jpeg', null=True, upload_to=''),
        ),
    ]
