# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-05 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180805_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/default_avatar.jpeg', null=True, upload_to=''),
        ),
    ]
