# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_skill_userskills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSkills',
            new_name='UserSkill',
        ),
    ]
