# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 11:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_auto_20180704_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.CharField(max_length=255)),
                ('is_filled', models.BooleanField(default=False)),
                ('filled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filled_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_position', to='projects.Project')),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='projects.Skill')),
            ],
        ),
    ]
