# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectposition',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='projects.Skill'),
        ),
    ]
