# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 11:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL),
        ),
    ]
