# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 12:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0007_auto_20180704_1117'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectapplication',
            unique_together=set([('position', 'applicant')]),
        ),
    ]
