# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-07 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20180704_1235'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectApplication',
            new_name='PositionApplication',
        ),
    ]
