# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-07 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20180707_2221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PositionApplication',
            new_name='Application',
        ),
        migrations.RenameModel(
            old_name='ProjectPosition',
            new_name='Position',
        ),
    ]
