# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20180710_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='timeline',
            field=models.CharField(max_length=30),
        ),
    ]
