# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20180721_0124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterField(
            model_name='applications',
            name='application_status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
