# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20180721_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
