# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 05:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0020_auto_20180721_1008'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together=set([('skill', 'user')]),
        ),
    ]
